?>

<div class="container">
    <h2> Add Composer</h2>

        <form action="?" method="post">

            <div class="formValues">
                <label for="ComposerLastName">Lastname:
                    <input type="text" name="ComposerLastname" class="formInput">
                </label>
            </div>

            <h3>Optional values:</h3>

            <div class="formValues">
                <label for="ComposerFirstname">Firstname:
                    <input type="text" name="ComposerFirstname" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="DateOfBirth">Date of Birth:
                    <input type="date" name="DateOfBirth" class="formInput">
                </label>
            </div>
            <div class="formValues">
                <label for="PlaceOfBirth">Place of Birth:
                    <input type="text" name="PlaceOfBirth" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="BirthCountry">Birthcountry:
                    <input type="text" name="BirthCountry" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="Deceased">Deceased:
                    <input type="date" name="Deceased" class="formInput">
                </label>
            </div>

            <input type="hidden" name="action" value="addComposer">

            <input type="submit" class="center">
        </form>
    </div>
