?>

<div class="container">
    <div class="innerleft">

        <form action="?" method="post">
            <h1> Insert new Composer </h1>

            <div class="formValues">
                <label for="ComposerLastName">Lastname:
                    <input type="text" name="ComposerLastname" class="formInput">
                </label>
            </div>

            <h2>Optional values:</h2>

            <div class="formValues">
                <label for="ComposerFirstname">Firstname:
                    <input type="text" name="ComposerFirstname" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="DateOfBirth">Date of Birth:
                    <input type="text" name="DateOfBirth" class="formInput">
                </label>
            </div>
            <div class="formValues">
                <label for="PlaceOfBirth">Place of Birth:
                    <input type="text" name="PlaceOfBirth" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="BirthCountry">Birthcountry:
                    <input type="text" name="BirthCountry" class="formInput">
                </label>
            </div>

            <div class="formValues">
                <label for="Deceased">Deceased:
                    <input type="text" name="Deceased" class="formInput">
                </label>
            </div>

            <input type="hidden" name="action" value="addComposer">

            <input type="submit" class="center">
        </form>
    </div>
</div>