<?php ?>
<div id="container">
    <div class="innerleft">

        <form action="?" method="post">
            <h1> Insert new Composer </h1>

            <label for="ComposerLastName" class="links">Lastname:</label>
            <input type="text" name="ComposerLastname" class="rechts">


            <h2>Optional values:</h2>

            <div class="links">Firstname:</div>
            <div class="rechts"><input type="text" name="ComposerFirstname"></div>

            <div class="links">Date of Birth: </div>
            <div class="rechts"><input type="date" name="DateOfBirth"></div>

            <div class="links">Place of Birth:</div>
            <div class="rechts"><input type="text" name="PlaceOfBirth"></div>

            <div class="links">Birthcountry: </div>
            <div class="rechts"><input type="text" name="BirthCountry"></div>

            <div class="links">Deceased: </div>
            <div class="rechts"><input type="text" name="Deceased"></div>

            <input type="hidden" name="action" value="addComposer">

            <input type="submit" class="center">
        </form>
    </div>
</div>