?>

<div id="navigation">
    <nav>
        <a href="?action=addComposer">Add Composer</a>
        <a href="?action=addSong">Add Song</a>
        <a href="?action=showSongs">Show Songs</a>
        <a href="?action=everyThing">ALLES</a>
    </nav>
</div>

<!--
Add Composer
Add Song
Add Playlist

Edit Composer
Edit Song
Edit Playlist

View Composer
View Song
View Playlist

// Add PDF to Compositions
// Compile PDF from Playlist PDF's
// Edit / Create PDF Vector based?
*/
-->