<!--fixmewithforeachloopthatremoves.phtml-->
<div id="navigation">
    <nav>
        <a href="?action=addComposer" class="navigation">Add Composer</a>
        <a href="?action=addSong" class="navigation">Add Song</a>
        <a href="?action=editSong" class="navigation">Edit Song</a>
        <a href="?action=editComposer" class="navigation">Edit Composer</a>
        <a href="?action=showSongs" class="navigation">Show Songs</a>
        <a href="?action=showComposers" class="navigation">Show Composers</a>
        <a href="?action=everyThing" class="navigation">ALLES</a>
    </nav>
</div>
<div class="flowcontainer">
<!--
Add Composer
Add Song
Add Playlist

Edit Composer
Edit Song
Edit Playlist

View Composer
View Song
View Playlist

// Add PDF to Compositions
// Compile PDF from Playlist PDF's
// Edit / Create PDF Vector based?
*/
-->