<div class="flowcontainer">
    <div class="container">
        <h1> Test </h1>
        <p> Test for main (als je dit main wilt noemen) </p>
        <p> Suf dat het main veld het beste in de footer kan komen maar goed</p>
        <p> Probleem: Als je iets heb ingevoerd verdwijnt dat vak terwijl je misschien nog verder wilt </p>
        <p>
            Welke content hier?
        <ul>
            <li> Print van Select all? </li>
            <li> Laatst toegevoegde werken? </li>
            <li> Playlists? </li>
            <li> Last viewed sheetmusic als pdf erin tonen? </li>
            <li> Bij invoer van nieuwe stukken of composities check tegen database om te kijken of het erin staat en dit printen in dit venster? </li>
        </ul>
        </p>
    </div>
</div>